services:
  ec2:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    network_mode: host
    volumes:
      - ./config:/etc/ec2-control-panel
    # ports:
    #   - 2720:2720
