[DEFAULT]
region = ap-northeast-1
availability_zone = ap-northeast-1d
vpc_id = vpc-042628b8054e095ef
security_group = sg-0004eeb822745ac47
ami_id = ami-0422aaf1bafed17b3
instance_type = r5.xlarge
instance_role = arn:aws:iam::185298664982:instance-profile/ec2
public_key = aws_ab
request_type = spot
bid_price = 1
volume_size = 512
instance_volume_size = 30

[ilya-novoselskiy]

[grachev]
availability_zone = ap-northeast-1b
